### ISSUE TITLE
Update the HIP markdown document 

### ISSUE THREAD

**Issue by sunway513** [RadeonOpenCompute/ROCm_Documentation#14]
@sriharikarnam could you help update the HIP markdown documents?
Like the following hip_bugs, those are out of sync for a while:
https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Programming_Guides/HIP-bug.rst
https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_bugs.md

**Comment by jlgreathouse** [comment]
As a member of RadeonOpenCompute, you should be able to do this as well, just to note.

You can convert the HIP .md file to .rst automatically [using Pandoc](https://bfroehle.com/2013/04/26/converting-md-to-rst/) and change the documentation .rst that way.

Anyway, I did that sync, so closing this issue.
