### ISSUE TITLE
What is the status of this repo?

### ISSUE THREAD

**Issue by Maxzor** [RadeonOpenCompute/ROCm_Documentation#140]
Dear @Rmalavally, I saw that you are somewhat alone in contributing to this gigantic repository.
Is it parked? Will documentation be split back to their respective repositories?
Best regards

**Comment by Rmalavally** [comment]
Thank you for reaching out, Maxzor. We are a team working on the content; however, I do manage this repository. 

Are there any concerns that I can help address? Please let me know.

Regards,
RM

**Comment by Maxzor** [comment]
I have not see much change recently, do you publish doc in batches with each ROCm release, meaning that a batch is coming for 5.0?

I am asking because I am considering packaging this repo in the official Debian packages.

**Comment by Maxzor** [comment]
I am having issues building here HEAD http://ix.io/3Ol0 today

**Comment by Rmalavally** [comment]
You are correct, Maxzor. We publish documentation for each ROCm release. 

This repository consists of obsolete documentation as well. If you are looking for something specific in release documentation, I am happy to share the relevant files with you. Let me know. 

Regards,
RM

**Comment by Maxzor** [comment]
@Rmalavally a batch indeed :)
Regards, Maxime
