### ISSUE TITLE
Add QEMU launch tutorial

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCm_Documentation#15]
I have been experience a number of problems with virsh/virt-installer when trying to set this up, notably not being able to stop the VM, or even gracefully shutdown/resert my computer

I have not had these issues with QEMU

One thing to note also generally is that it seems much simpler to use virtualization with more than one GPU, such that the main host GPU can remain as such, and any additional can be put towards vfio-pci

my launch command looks like this

```
qemu-system-x86_64 -m 10048 \
 -net nic,model=virtio \
 -net user,hostfwd=tcp::8022-:22 \
 -cpu host -smp 4  \
 -enable-kvm \
 -nographic  \
 -device virtio-rng-pci \
 -drive file="img.qcow2",media=disk,snapshot=off,if=virtio \
 -device vfio-pci,host=0c:00.0,x-vga=off -device vfio-pci,host=0c:00.1
```

**Comment by Avatat** [comment]
ROCm driver has huge problems with passing through to VM.
When I kill VM, a device is getting back to the host, the driver is loading and crashing. No screen, no working /dev/kfd and ROCm stack.

**Comment by fxkamd** [comment]
Hi @Avatat , Alex Deucher just posted a patch series that should address your problem. See https://lists.freedesktop.org/archives/amd-gfx/2019-January/030303.html. This should get included in the next ROCm release.
