### ISSUE TITLE
Not working example code

### ISSUE THREAD

**Issue by sasf54** [RadeonOpenCompute/ROCm_Documentation#25]
there are some issues in your example code, which makes learning more difficult :(
Opencl-programming-guide:
there are some line of code, that stuck under comment, because of formatting

Example code 1.
Block 1.:
the example kernel code was not quoted into a string 
platform and device is not defined 

Block 2.:
the example kernel code was not quoted into a string 
there's device, but still no platform
context is not defined (part of comment)

clCreateBuffer( context, CL_MEM_WRITE_ONLY, // line / command just hung up

/ 6. is not a comment :(
size_t global_work_size = NWITEMS; // is a new line
cl_uint *ptr; // new line

**Comment by jlgreathouse** [comment]
1404a9d9fe0f3d2552d34ce825182d799964ea3f should fix this issue for all of the examples I could find in the OpenCL programming guide. Thanks for pointing this out!
