### ISSUE TITLE
Lack of memory management docs

### ISSUE THREAD

**Issue by Avatat** [RadeonOpenCompute/ROCm_Documentation#27]
Memory management functions documentation doesn't exist: https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP_API/Memory-Management.html#hipmalloc

![screenshot_2019-01-08 memory management rocm documentation latest documentation](https://user-images.githubusercontent.com/11491256/50881866-cbb2e880-1397-11e9-828d-5f7e7e8d65cc.png)

**Comment by jlgreathouse** [comment]
@mangupta may be the best person to address this

**Comment by mangupta** [comment]
I believe there is some issue with linking the doxygen documentation of all the ROCm components with readthedocs. Since most of the HIP API documentation is in doxygen format, it is not showing up on readthedocs.

**Comment by JMadgwick** [comment]
I believe that [this page](https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/ROCr-Runtime.html#rocr-api) has a similar problem.
It is for the 'ROCr System Runtime API' and is linked to from [here](https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/ROCm-API-References.html).

The page linked in the original issue has been fixed however.

**Comment by sriharikarnam** [comment]
Please refer the 'ROCr System Runtime API' here:
https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/ROCr-API.html#rocr-api
