### ISSUE TITLE
Error in the pytorch documentation at "Deep Learning on Rocm"

### ISSUE THREAD

**Issue by fradav** [RadeonOpenCompute/ROCm_Documentation#28]
Hello,

```bash
~$ docker pull rocm/pytorch:rocm2.0
Error response from daemon: manifest for rocm/pytorch:rocm2.0 not found
```
And when we look at:
https://hub.docker.com/r/rocm/pytorch/tags
there is no such thing than a rocm2.0 tag.

Please upload the new image?
Regards,

**Comment by sriharikarnam** [comment]
A new image has been uploaded.
Please find it below 
https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html#recommended-install-using-published-pytorch-rocm-docker-image
