### ISSUE TITLE
Warning for "HCC Deprecation Notice" missing

### ISSUE THREAD

**Issue by seesturm** [RadeonOpenCompute/ROCm_Documentation#37]
According to the [ROCm github page](https://github.com/RadeonOpenCompute/ROCm) HCC is deprecated and will be discontinued already within 2019. Please add a warning to the documentation - especially to [Programming-Guides]( https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Programming_Guides/Programming-Guides.rst).

It appears to serve as the basis for choosing the language. And the way it is written now suggests that HCC should be used when one wants to start a new project with specifically targeting AMDGPU hardware.

**Comment by sriharikarnam** [comment]
Deprecation Notice for HCC has been mentioned in ROCm Installation Guide.
Please refer https://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html#deprecation-notice

**Comment by seesturm** [comment]
Of course is it mentioned somewhere else. I even mentioned one place where to find this information.

But this issue is not about putting it into release notes but about putting a warning into the programming guides.

**Comment by JMadgwick** [comment]
I think that all mentions of HC should probably be removed and replaced with a deprecation notice that points to page where all the HC information is archived.
AMD seems to have buried their hand in the sand over documentation. Generally it's very incompletely and (other than the main Github page) mostly outdated. Even the Github page is wrong, stating GPUs that were dropped 8 months ago are supported.

You could try making a pull request but these seem to just be ignored by the devs.
