### ISSUE TITLE
Readthedocs API reference broken

### ISSUE THREAD

**Issue by ams-cs** [RadeonOpenCompute/ROCm_Documentation#41]
The web page at [readthedocs](https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/ROCr-Runtime.html#rocr-api) is just a bunch of errors.

Example:
```
Runtime Notification

Warning

doxygenenum: Cannot find enum “hsa_status_t” in doxygen xml output for project “ReadTheDocs-Breathe” from directory: xml/

Warning

doxygenfunction: Cannot find function “hsa_status_string” in doxygen xml output for project “ReadTheDocs-Breathe” from directory: xml/
```

**Comment by sriharikarnam** [comment]
Please refer the 'ROCr Runtime Documentation' here

 https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/ROCr-API.html#rocr-api
