### ISSUE TITLE
Ads on ROCm documentation

### ISSUE THREAD

**Issue by kiritigowda** [RadeonOpenCompute/ROCm_Documentation#46]
**Can we disable or remove ads on ROCm documentation website?**

<img width="873" alt="ads-rocm" src="https://user-images.githubusercontent.com/16549273/66338283-ad155a00-e8f5-11e9-9354-4f7d42c21482.PNG">

**Comment by sriharikarnam** [comment]
ROCm Documentation is built on Read the Docs, a open source platform and there is no provision to enable or disable ads.

**Comment by sriharikarnam** [comment]
ROCm Documentation is built on Read the Docs, a open source platform and there is no provision to enable or disable ads.
