### ISSUE TITLE
Kernel arguments and launching documentation outdated

### ISSUE THREAD

**Issue by rwvo** [RadeonOpenCompute/ROCm_Documentation#48]
Several documents contain `hipLaunchKernel` instead of `hipLaunchKernelGGL`, and several kernel examples show a `hipLaunchParm` first argument. Should be easy to find those by grepping.

**Comment by sriharikarnam** [comment]
I have replaced “hipLaunchKernel” with “hipLaunchKernelGGL” and removed the ‘hipLaunchParm’ argument for the kernels called.
