### ISSUE TITLE
Incorrect installation instructions

### ISSUE THREAD

**Issue by souravzzz** [RadeonOpenCompute/ROCm_Documentation#53]
https://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html#ubuntu

https://rocm.github.io/ROCmInstall.html#Ubuntu

Copy pasting the instructions (wget ...) didn't work (probably due to HTML rendering)

**Comment by atamazov** [comment]
They were warned, but preferred to ignore:  https://github.com/RadeonOpenCompute/ROCm_Documentation/pull/51#pullrequestreview-324745331

**Comment by sriharikarnam** [comment]
I have made the corrections
Please find it below
https://rocm.github.io/ROCmInstall.html

**Comment by atamazov** [comment]
@sriharikarnam Thanks!
