### ISSUE TITLE
Contribution question (Documentation)

### ISSUE THREAD

**Issue by 7022Andre** [RadeonOpenCompute/ROCm_Documentation#7]
Hi there @gstoner,

Thank you so much for offering an alternative to the AMD GPUPRO drivers and for maintaining all related ROCm repos. Appreciate it.
While going through the instructions at https://rocm.github.io I noticed some inconsistencies and unclear items. I also found this page (http://rocm-documentation.readthedocs.io) which I assume is connected to this repo.

Here's what I'd like to do: Go through the documentation, fix content and create a pull request. I personally like how the documentation is structured at http://rocm-documentation.readthedocs.io compared to https://rocm.github.io.

What's the best way to help with that? Is new content to this repo (https://github.com/RadeonOpenCompute/ROCm_Documentation) automatically pushed to https://rocm.github.com?

Thanks,
Andre

**Comment by gstoner** [comment]
Thanks for point this out,  We need to go back and edit these instructions,  But contributions are welcome

Greg


The documentation for the website for rocm.github.io<http://rocm.github.io> is at  https://github.com/ROCm/ROCm.github.io
This document repo https://github.com/RadeonOpenCompute/ROCm_Documentation  back http://rocm-documentation.readthedocs.io. so any edit will address this repo.


If you do commit I will go do assessment on acceptance.  So it pretty easy to do commitment.

Greg

**Comment by 7022Andre** [comment]
Thanks @gstoner  What's more important to work on/update right now: https://github.com/ROCm/ROCm.github.io or https://github.com/RadeonOpenCompute/ROCm_Documentation?
