### ISSUE TITLE
usermod: group 'render' does not exist

### ISSUE THREAD

**Issue by tugot17** [RadeonOpenCompute/ROCm_Documentation#97]
**Platform: Ubuntu 18.04**

When I try to add user to the render  group using `sudo usermod -a -G render piotr` I get: `usermod: group 'render' does not exist
`

I have successfully installed rocm package, however `render` group didn't appear.

Is there anything that can be done about it?

**Comment by xuhuisheng** [comment]
Please use video group in ubuntu 18.04. the render group is used for ubuntu 20.04.
