### ISSUE TITLE
Get hipErrorNoBinaryForGpu when running the HIP Sample

### ISSUE THREAD

**Issue by tomac204** [RadeonOpenCompute/ROCm_Documentation#99]
I tried to follow the instructions on page https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html# to compile and install the basic rocm3.7 compnents manually, kernel driver has already been installed and loaded successfully.

HIP    ROCm-CompilerSupport    rocminfo    ROCR-Runtime    ROCm-Device-Libs    ROCT-Thunk-Interface    ROCm-OpenCL-Runtime    ROCclr    llvm-project

When I ran HIP/samples/0_Intro/square example, I got following output:
LoadLib(libhsa-amd-aqlprofile64.so) failed: libhsa-amd-aqlprofile64.so: cannot open shared object file: No such file or directory
/work/HIP/rocclr/hip_code_object.cpp:92: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Aborted (core dumped)

Any advice for these errors?
Which project/repository will generate libhsa-amd-aqlprofile64.so?
How to fix hipErrorNoBinaryForGpu?

the outputs of rocminfo and hipconfig are in the attachment.
[hipconfig.txt](https://github.com/RadeonOpenCompute/ROCm_Documentation/files/5186440/hipconfig.txt)
[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm_Documentation/files/5186441/rocminfo.txt)

**Comment by Rmalavally** [comment]
Thank you for reaching out. We are checking with the HIP team and will update you once we hear from them. 

AMD ROCm Documentation Team

**Comment by tomac204** [comment]
Sorry, I realize that I opened a ticket in a wrong repo, I have create the same ticket in HIP repo.
Thanks.
